name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Replace Placeholder with Secrets
        env:
          WORKER_URL: ${{ secrets.WORKER_URL }}
          GAS_URL: ${{ secrets.GAS_URL }}
        run: |
          # HTML側の __WORKER_URL__ と __GAS_URL__ に合わせて変更
          sed -i "s|__WORKER_URL__|${WORKER_URL}|g" index.html
          sed -i "s|__GAS_URL__|${GAS_URL}|g" index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
